### ISSUE TITLE
Cannot install with `gem install etc`, missing `constdefs.h`

### ISSUE THREAD

**Issue by najamelan** [ruby/etc#3]
It seems that when installing with `gem` the file `constdefs.h` does not get generated, thus building the native extension fails.
```
fedora 26
gem  --version: 2.6.13
ruby --version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
```
both running as root or as normal user fail.

----
To reproduce (more or less)
```
as root:
dnf install ruby rubygems
gem install etc 
```

**Comment by najamelan** [comment]
Actually, checking with `irb`, `etc` seems to be available, is it shipped with stock ruby install and not supposed to be installed with ´gem´?

**Comment by stomar** [comment]
I can confirm the installation failure (on Ubuntu).

Regarding your last comment:

The gem exists because with Ruby 2.5 the stdlib has been „gemified“. etc will continue to get shipped with Ruby releases (for the time being—occasionally libraries get removed), but it will be possible to update the library independently of Ruby by installing a newer gem version, e.g. in case of security fixes.

Currently it shouldn‘t be necessary for you to install this gem.

**Comment by najamelan** [comment]
Yes, thank you for responding. I figured out too late that it was included in stock ruby install.

**Comment by stomar** [comment]
Nevertheless this must be fixed.
